### PR TITLE
📄 Docs: Remove the bullet points from the features list in the "About this recipe" section.

### PR DESCRIPTION
**Pull request by harshsinghatz**
## Changes
- Removed the bullet point from these files
          1.  v2/community/introduction.mdx
          2. v2/emailpassword/introduction.mdx
          3. v2/passwordless/introduction.mdx
          4. v2/session/introduction.mdx
          5. v2/thirdparty/introduction.mdx
          6. v2/thirdpartyemailpassword/introduction.mdx

## Related issues
- https://github.com/supertokens/docs/issues/227

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
hey! The checklist is rendering like this now:
Screenshot 2022-02-20 at 12 15 56

Is this intentional?

**Comment by harshsinghatz** [comment]
My bad! , no that was not intentional.
Can you guide for this error:
_Error: ENOENT: no such file or directory, open 'C:\Users\hs908\Desktop\harsh\projects\Open Source\docs\v2\auth-react\emailpassw'rd\redpassw'rd\redirect-to-auth.mdx_

**Comment by rishabhpoddar** [comment]
I'm not sure about that error as I have never faced it. What command did you run? And can I see the full error output?

**Comment by harshsinghatz** [comment]
os1
This is the full screenshot of the error .
Commands that i executed before this error

- npm i -d
- npm run start

**Comment by rishabhpoddar** [comment]
hey @harshsinghatz can you do a git pull from master and try again?

**Comment by harshsinghatz** [comment]
I tried but it's not working.
So now I am using Gitpod and it's working so I will fix that in no time!!

**Comment by harshsinghatz** [comment]
Hey @rishabhpoddar,
I have done the changes in the files please do check it!

**Comment by rishabhpoddar** [comment]
Thanks @harshsinghatz!

**Comment by harshsinghatz** [comment]
My pleasure!, but why isn't the changes reflected on the website?

**Comment by rishabhpoddar** [comment]
It's on the test site here: https://test.supertokens.com/docs/community/introduction

Once we push this to prod, it will be reflected on the main site :)

**Comment by harshsinghatz** [comment]
Ok got it 👍

**Pull request merged**
