### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by zvictor**
minor typo fix 😊

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
hey @zvictor the docs you modified is actually automatically copied from this page: https://github.com/supertokens/docs/blob/master/v2/session/common-customizations/sessions/with-jwt/about.mdx

So you will need to fix the typo from the above page instead, and that will get propagated to the other recipe docs during the build process.

**Comment by zvictor** [comment]
I can do that, no problem.

I ended up here after clicking in the "edit page" link in the docs website. Shouldn't that link point to the right file then?

**Comment by rishabhpoddar** [comment]
@zvictor it actually does link to the right page from Docusauru's point of view. But we have made a custom plugin which allows docs to be copied across recipes. This is something that docusaurus' link to github is not aware of and hence doesn't link to the true source.

That being said, we will investigate if we can make it link to the true source.

**Comment by zvictor** [comment]
> This is something that docusaurus' link to github is not aware of and hence doesn't link to the true source. That being said, we will investigate if we can make it link to the true source.

Yes, that's what I meant 🙂
It should save you time in the future when others do the same mistake I just did.

**Pull request closed without merging**
