### PR TITLE
Update init.mdx

### PR DESCRIPTION
**Pull request by michaelgrigoryan25**

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
thanks for this PR. There are other recipes too where this change needs to be made (for consistency purposes). I can make them if you like, else you can add to this PR.

**Comment by michaelgrigoryan25** [comment]
I think merging it, for now, will be ok. I may not be able to go through the whole documentation right now.

**Comment by rishabhpoddar** [comment]
Sounds good.

**Comment by rishabhpoddar** [comment]
Thanks.

**Pull request merged**
