### PR TITLE
docs: update images to reflect changes after button CSS change

### PR DESCRIPTION
**Pull request by alisher-aituarov**
## Summary of change
Updates the screenshots for recipes that involve thirdparty providers

## Related issues
- https://github.com/supertokens/supertokens-core/issues/540
- https://github.com/supertokens/supertokens-auth-react/pull/621

## Checklist
- [ ] Algolia search needs to be updated? (If there is a new sub docs project, then yes)
- [ ] Sitemap needs to be updated? (If there is a new sub docs project, then yes)
- [x] Checked for broken links? (Run `cd v2 && MODE=production npx docusaurus build`)
- [x] Changes required to the demo apps corresponding to the docs?

### CODE REVIEW

**Review by porcellus — CHANGES_REQUESTED** [review]
- Please update the PR title to match conventional commits or remove "chore"; matching the conventional commits is more important in the SDK repos and not that useful here
- Fix the title to explain the point of the PR. Just saying update docs in the title of a PR into the "docs" repo isn't very descriptive :)
Something like: `docs: update images after social button CSS change` is fine.

- Please also check these images. If any of them are unused, you can delete them.
```
v2/static/img/thirdpartypasswordless-email.png
v2/static/img/thirdpartypasswordless-no-email.png
v2/static/img/thirdpartypasswordless/signinup-light.png
v2/static/img/recipe-tabs/recipe-passwordless-social.png
v2/static/img/recipe-tabs/recipe-social.png
v2/static/img/thirdparty/override/find-component
v2/static/img/thirdparty/dark-theme.png
v2/static/img/thirdparty/inspect-button.png
v2/static/img/thirdparty/react-override-octocat.png
v2/static/img/thirdparty/title-border.png
v2/static/img/thirdpartyemailpassword/override/find-component.png
v2/static/img/thirdpartyemailpassword/custom-field-name-signup.png
v2/static/img/thirdpartyemailpassword/modified-formfields.png
v2/static/img/thirdpartyemailpassword/react-override-octocat.png
v2/static/img/thirdpartyemailpassword/signin-dark.png
v2/static/img/thirdpartyemailpassword/signin-light.png
v2/static/img/thirdpartyemailpassword/signup-centered-blue-button.png
v2/static/img/thirdpartyemailpassword/signup-dark.png
v2/static/img/thirdpartyemailpassword/signup-invalid-age-light.png
v2/static/img/thirdpartyemailpassword/signup-light.png
v2/static/img/thirdpartyemailpassword/signup-with-name-and-age.png
v2/static/img/thirdpartypasswordless/override/find-component.png
```

**Comment by alisher-aituarov** [comment]
> * Please update the PR title to match conventional commits or remove "chore"; matching the conventional commits is more important in the SDK repos and not that useful here
> * Fix the title to explain the point of the PR. Just saying update docs in the title of a PR into the "docs" repo isn't very descriptive :)
>   Something like: `docs: update images after social button CSS change` is fine.
> * Please also check these images. If any of them are unused, you can delete them.
> 
> ```
> v2/static/img/thirdpartypasswordless-email.png
> v2/static/img/thirdpartypasswordless-no-email.png
> v2/static/img/thirdpartypasswordless/signinup-light.png
> v2/static/img/recipe-tabs/recipe-passwordless-social.png
> v2/static/img/recipe-tabs/recipe-social.png
> v2/static/img/thirdparty/override/find-component
> v2/static/img/thirdparty/dark-theme.png
> v2/static/img/thirdparty/inspect-button.png
> v2/static/img/thirdparty/react-override-octocat.png
> v2/static/img/thirdparty/title-border.png
> v2/static/img/thirdpartyemailpassword/override/find-component.png
> v2/static/img/thirdpartyemailpassword/custom-field-name-signup.png
> v2/static/img/thirdpartyemailpassword/modified-formfields.png
> v2/static/img/thirdpartyemailpassword/react-override-octocat.png
> v2/static/img/thirdpartyemailpassword/signin-dark.png
> v2/static/img/thirdpartyemailpassword/signin-light.png
> v2/static/img/thirdpartyemailpassword/signup-centered-blue-button.png
> v2/static/img/thirdpartyemailpassword/signup-dark.png
> v2/static/img/thirdpartyemailpassword/signup-invalid-age-light.png
> v2/static/img/thirdpartyemailpassword/signup-light.png
> v2/static/img/thirdpartyemailpassword/signup-with-name-and-age.png
> v2/static/img/thirdpartypasswordless/override/find-component.png
> ```

- fixed the title
- I was told it is better to avoid changes that are not in the scope of the work that is being done

**Comment by porcellus** [comment]
Fair enough. Still, please check if those images are used in the documentation; this one is used but not updated:
https://deploy-preview-557--admiring-bhabha-7b1be9.netlify.app/docs/thirdpartyemailpassword/advanced-customizations/react-component-override/usage (`v2/static/img/thirdpartyemailpassword/override/find-component.png`)

**Review by porcellus — CHANGES_REQUESTED** [review]
There are still images, e.g.: https://deploy-preview-557--admiring-bhabha-7b1be9.netlify.app/docs/thirdpartyemailpassword/common-customizations/signup-form/adding-fields

**Review by porcellus — APPROVED** [review]

**Pull request merged**
