### PR TITLE
[FIX] injection token variable & config filename

### PR DESCRIPTION
**Pull request by olhapi**
## Summary of change
Injection token variable wasn't consistent across docs and overall solution was broken. Same with config filename.

### CODE REVIEW

**Comment by olhapi** [comment]
hey @rishabhpoddar 
Can you check this PR? I've fixed nestjs guide.

**Comment by rishabhpoddar** [comment]
@olhapi thank you for the PR. I have marked @porcellus as the reviewer since he was the one who wrote this section of the docs in the first place :)

**Comment by porcellus** [comment]
Good catch, thanks for the PR :) sorry about the late reply.

The only thing is, that the guides for other recipes (emailpassword, session, thirdparty) need this update as well before we can merge it.

**Comment by olhapi** [comment]
@porcellus you're welcome. Added fixes to another strategies 👍

**Review by porcellus — APPROVED** [review]
Great, thanks :)

**Comment by porcellus** [comment]
Hi, since you are (or were recently) implementing us in NestJS, this PR may also interest you #177; we've just updated the guide again.

**Pull request merged**
